[package]
name = "gui"
version = "0.1.0"
authors = ["Sorenon <sorenonandstuffs@gmail.com>"]
edition = "2018"

[dependencies]
iced = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
common = { path = "../common" }